# Generated by Django 4.2 on 2023-05-04 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Walyuta')),
            ],
            options={
                'verbose_name': 'Walyuta',
                'verbose_name_plural': 'Walyutalar',
            },
        ),
        migrations.CreateModel(
            name='MustPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Bergidaryn ady')),
                ('last_name', models.CharField(max_length=200, verbose_name='Bergidaryn Familiyasy')),
                ('birthday', models.DateField(verbose_name='Doglan senesi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Bergidar',
                'verbose_name_plural': 'Bergidarlar',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Algydaryn ady')),
                ('last_name', models.CharField(max_length=200, verbose_name='Algydaryn Familiyasy')),
                ('birthday', models.DateField(verbose_name='Doglan senesi')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Algydar',
                'verbose_name_plural': 'Algydarlar',
            },
        ),
        migrations.CreateModel(
            name='RecipientChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Algydaryn ady')),
                ('last_name', models.CharField(max_length=200, verbose_name='Algydaryn Familiyasy')),
                ('birthday', models.DateField(verbose_name='Doglan senesi')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.recipient')),
            ],
            options={
                'verbose_name': 'Algydaryn cagasy',
                'verbose_name_plural': 'Algydarlaryn cagalary',
            },
        ),
        migrations.CreateModel(
            name='MustPayReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sonky tolenen mocberi')),
                ('last_payment_date', models.DateField(verbose_name='Tolenen resminamanyn senesi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Tolegi tassyklayan resminama')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.currency')),
                ('own_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.mustpay')),
            ],
            options={
                'verbose_name': 'Toleg',
                'verbose_name_plural': 'Tolegler',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='report.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(max_length=100, verbose_name='Yerine yetiryan')),
                ('ruling', models.CharField(max_length=100, verbose_name='Karary cykaran')),
                ('ruling_date', models.DateField(verbose_name='Kararyn senesi')),
                ('note', models.TextField(blank=True, verbose_name='Bellik')),
                ('status', models.BooleanField(default=False, verbose_name='Ishin statusy')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.category', verbose_name='Bolum')),
                ('must_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.mustpay', verbose_name='Bergidaryn ady, familiyasy')),
                ('must_pay_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.mustpayreceipt', verbose_name='Bergidaryn tolegleri')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.recipient', verbose_name='Algydaryn ady, familiyasy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy')),
            ],
            options={
                'verbose_name': 'Aliment',
                'verbose_name_plural': 'Alimentlar',
            },
        ),
    ]
