# Generated by Django 4.2 on 2023-05-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimony',
            name='must_pay_receipt',
        ),
    ]
